[package]
name = "trek-core"
version = "0.1.0"
authors = ["Fangdun Cai <cfddream@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
http = "0.1.18"
hyper = "0.13.0-alpha.1"
serde = { version = "1.0.101", features = ["derive"] }
serde_json = "1.0.40"
serde_qs = "0.5.0"
serde_urlencoded = "0.5.1"
cookie = "0.12.0"
futures-preview = "=0.3.0-alpha.18"
multipart-async = { git = "https://github.com/abonander/multipart-async.git", branch = "master", features = ["server", "hyper"], default-features = false }

[dev-dependencies]
